# Generated by Django 2.1.4 on 2018-12-05 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0004_auto_20181205_1701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='name',
            new_name='company',
        ),
    ]
